[package]
name = "tonic-tls"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
async-stream.workspace = true
tracing.workspace = true
futures.workspace = true

tower.workspace = true
tonic.workspace = true
hyper.workspace = true
hyper-util.workspace = true